import { describe, it, expect } from '@jest/globals';
import { mappedFunctions } from "./ConditionMappers";

describe("Condition mapper functions", () => {
    describe("String conditions", () => {
        it.each([
            [mappedFunctions.string.equal, "one", "one", true],
            [mappedFunctions.string.equal, "two", "two", true],
            [mappedFunctions.string.equal, "", "", true],
            [mappedFunctions.string.equal, "one", "two", false],
            [mappedFunctions.string.equal, "two", "one", false],
            [mappedFunctions.string.equal, "2", 2, false],
            [mappedFunctions.string.equal, 2, "2", false],
            [mappedFunctions.string.equal, "one", null, false],
            [mappedFunctions.string.equal, "one", undefined, false],
            [mappedFunctions.string.equal, "one", "onE", false],
            [mappedFunctions.string.equal, "one", "oNe", false],
            [mappedFunctions.string.equal, "one", "oNE", false],
            [mappedFunctions.string.equal, "one", "One", false],
            [mappedFunctions.string.equal, "one", "OnE", false],
            [mappedFunctions.string.equal, "one", "ONe", false],
            [mappedFunctions.string.equal, "one", "ONE", false],
            [mappedFunctions.string.not_equal, "one", "one", false],
            [mappedFunctions.string.not_equal, "two", "two", false],
            [mappedFunctions.string.not_equal, "", "", false],
            [mappedFunctions.string.not_equal, "one", "two", true],
            [mappedFunctions.string.not_equal, "two", "one", true],
            [mappedFunctions.string.not_equal, "2", 2, true],
            [mappedFunctions.string.not_equal, 2, "2", true],
            [mappedFunctions.string.not_equal, "one", null, true],
            [mappedFunctions.string.not_equal, "one", undefined, true],
            [mappedFunctions.string.not_equal, "one", "onE", true],
            [mappedFunctions.string.not_equal, "one", "oNe", true],
            [mappedFunctions.string.not_equal, "one", "oNE", true],
            [mappedFunctions.string.not_equal, "one", "One", true],
            [mappedFunctions.string.not_equal, "one", "OnE", true],
            [mappedFunctions.string.not_equal, "one", "ONe", true],
            [mappedFunctions.string.not_equal, "one", "ONE", true],
            [mappedFunctions.string.in, "text", "text", true],
            [mappedFunctions.string.in, "text", "this is some text", true],
            [mappedFunctions.string.in, "Text", "text", false],
            [mappedFunctions.string.in, "text", "Text", false],
            [mappedFunctions.string.in, "Text", "this is some text", false],
            [mappedFunctions.string.in, "string", "this is some text", false],
            [mappedFunctions.string.in, "", "this is some text", true],
            [mappedFunctions.string.not_in, "text", "text", false],
            [mappedFunctions.string.not_in, "text", "this is some text", false],
            [mappedFunctions.string.not_in, "Text", "text", true],
            [mappedFunctions.string.not_in, "text", "Text", true],
            [mappedFunctions.string.not_in, "Text", "this is some text", true],
            [mappedFunctions.string.not_in, "string", "this is some text", true],
            [mappedFunctions.string.not_in, "", "this is some text", false],
            [mappedFunctions.string.begins_with, "text", "text", true],
            [mappedFunctions.string.begins_with, "this is some text", "this", true],
            [mappedFunctions.string.begins_with, "this is some text", "this is", true],
            [mappedFunctions.string.begins_with, "this is some text", "", true],
            [mappedFunctions.string.begins_with, "this is some text", "This", false],
            [mappedFunctions.string.begins_with, "this is some text", "is", false],
            [mappedFunctions.string.not_begins_with, "text", "text", false],
            [mappedFunctions.string.not_begins_with, "this is some text", "this", false],
            [mappedFunctions.string.not_begins_with, "this is some text", "this is", false],
            [mappedFunctions.string.not_begins_with, "this is some text", "", false],
            [mappedFunctions.string.not_begins_with, "this is some text", "This", true],
            [mappedFunctions.string.not_begins_with, "this is some text", "is", true],
            [mappedFunctions.string.contains, "text", "text", true],
            [mappedFunctions.string.contains, "this is some text", "some", true],
            [mappedFunctions.string.contains, "this is some more text", "text", true],
            [mappedFunctions.string.contains, "this is some text", "this is", true],
            [mappedFunctions.string.contains, "this is some text", "This IS", false],
            [mappedFunctions.string.contains, "this is some text", "nothing", false],
            [mappedFunctions.string.not_contains, "text", "text", false],
            [mappedFunctions.string.not_contains, "this is some text", "some", false],
            [mappedFunctions.string.not_contains, "this is some more text", "text", false],
            [mappedFunctions.string.not_contains, "this is some text", "this is", false],
            [mappedFunctions.string.not_contains, "this is some text", "This IS", true],
            [mappedFunctions.string.not_contains, "this is some text", "nothing", true],
            [mappedFunctions.string.ends_with, "text", "text", true],
            [mappedFunctions.string.ends_with, "this is some text", "text", true],
            [mappedFunctions.string.ends_with, "this is some text", "some text", true],
            [mappedFunctions.string.ends_with, "this is some text", "this is", false],
            [mappedFunctions.string.ends_with, "this is some text", "Some text", false],
            [mappedFunctions.string.not_ends_with, "text", "text", false],
            [mappedFunctions.string.not_ends_with, "this is some text", "text", false],
            [mappedFunctions.string.not_ends_with, "this is some text", "some text", false],
            [mappedFunctions.string.not_ends_with, "this is some text", "this is", true],
            [mappedFunctions.string.not_ends_with, "this is some text", "Some text", true],
            [mappedFunctions.string.is_empty, "", undefined, true],
            [mappedFunctions.string.is_empty, "text", undefined, false],
            [mappedFunctions.string.is_empty, " ", undefined, false],
            [mappedFunctions.string.is_empty, "\t", undefined, false],
            [mappedFunctions.string.is_not_empty, "", undefined, false],
            [mappedFunctions.string.is_not_empty, "text", undefined, true],
            [mappedFunctions.string.is_not_empty, " ", undefined, true],
            [mappedFunctions.string.is_not_empty, "\t", undefined, true],
            [mappedFunctions.string.is_null, null, undefined, true],
            [mappedFunctions.string.is_null, undefined, undefined, true],
            [mappedFunctions.string.is_null, "", undefined, false],
            [mappedFunctions.string.is_null, " ", undefined, false],
            [mappedFunctions.string.is_null, "hello", undefined, false],
            [mappedFunctions.string.is_not_null, null, undefined, false],
            [mappedFunctions.string.is_not_null, undefined, undefined, false],
            [mappedFunctions.string.is_not_null, "", undefined, true],
            [mappedFunctions.string.is_not_null, " ", undefined, true],
            [mappedFunctions.string.is_not_null, "hello", undefined, true]
        ])("Check %s with %s and %s returns %s", (fn, a, b, expected) => {
            expect(fn(a, b)).toBe(expected);
        });
    });

    describe("Boolean conditions", () => {
        it.each([
            [mappedFunctions.boolean.equal, false, false, true],
            [mappedFunctions.boolean.equal, false, true, false],
            [mappedFunctions.boolean.equal, true, false, false],
            [mappedFunctions.boolean.equal, true, true, true],
            [mappedFunctions.boolean.not_equal, false, false, false],
            [mappedFunctions.boolean.not_equal, false, true, true],
            [mappedFunctions.boolean.not_equal, true, false, true],
            [mappedFunctions.boolean.not_equal, true, true, false],
            [mappedFunctions.boolean.is_null, null, undefined, true],
            [mappedFunctions.boolean.is_null, undefined, undefined, true],
            [mappedFunctions.boolean.is_null, true, undefined, false],
            [mappedFunctions.boolean.is_null, false, undefined, false],
            [mappedFunctions.boolean.is_not_null, null, undefined, false],
            [mappedFunctions.boolean.is_not_null, undefined, undefined, false],
            [mappedFunctions.boolean.is_not_null, true, undefined, true],
            [mappedFunctions.boolean.is_not_null, false, undefined, true]
        ])("Check %s with %s and %s returns %s", (fn, a, b, expected) => {
            expect(fn(a, b)).toBe(expected);
        });
    });

    for (const type of ["integer", "double"]) { // START integer, double LOOP
        describe(`${type} functions`, () => {
            const sut = mappedFunctions[type];

            it.each([
                [sut.equal, 0, 0, true],
                [sut.equal, 0, 1, false],
                [sut.equal, 1, 0, false],
                [sut.equal, 1, 1, true],
                [sut.equal, 1, 10, false],
                [sut.not_equal, 0, 0, false],
                [sut.not_equal, 0, 1, true],
                [sut.not_equal, 1, 0, true],
                [sut.not_equal, 1, 1, false],
                [sut.not_equal, 1, 10, true],
                [sut.in, 1, 123, true],
                [sut.in, 2, 123, true],
                [sut.in, 3, 123, true],
                [sut.in, 4, 123, false],
                [sut.in, 23, 123, true],
                [sut.in, 12, 123, true],
                [sut.in, 34, 123, false],
                [sut.in, 0, 123, false],
                [sut.less, 1, 2, true],
                [sut.less, 2, 2, false],
                [sut.less, 3, 2, false],
                [sut.less_or_equal, 1, 2, true],
                [sut.less_or_equal, 2, 2, true],
                [sut.less_or_equal, 3, 2, false],
                [sut.greater, 1, 2, false],
                [sut.greater, 2, 2, false],
                [sut.greater, 3, 2, true],
                [sut.greater_or_equal, 1, 2, false],
                [sut.greater_or_equal, 2, 2, true],
                [sut.greater_or_equal, 3, 2, true],
                [sut.between, 1, [2, 3], false],
                [sut.between, 1, [1, 3], true],
                [sut.between, 2, [1, 3], true],
                [sut.between, 3, [1, 3], true],
                [sut.between, 4, [1, 3], false],
                [sut.not_between, 1, [2, 3], true],
                [sut.not_between, 1, [1, 3], false],
                [sut.not_between, 2, [1, 3], false],
                [sut.not_between, 3, [1, 3], false],
                [sut.not_between, 4, [1, 3], true],
                [sut.is_null, null, undefined, true],
                [sut.is_null, undefined, undefined, true],
                [sut.is_null, 0, undefined, false],
                [sut.is_null, -10, undefined, false],
                [sut.is_not_null, null, undefined, false],
                [sut.is_not_null, undefined, undefined, false],
                [sut.is_not_null, 0, undefined, true],
                [sut.is_not_null, -10, undefined, true]
            ])(type + "should check %s with %d and %d returns %s", (fn, a, b, expected) => {
                expect(fn(a, b)).toBe(expected);
            });
        });
    } // END integer, double LOOP

    describe("Date tests", () => { // This is not a "clean" test - this errors depending on the date you run it (seriously)
        const sut = mappedFunctions["date"];
        const baseDate = new Date(2012, 8, 15, 0, 0, 0, 0);
        const nowPlusTwo = new Date(baseDate);
        nowPlusTwo.setDate(baseDate.getDate() + 2);
        const nowMinusTwo = new Date(baseDate);
        nowMinusTwo.setDate(baseDate.getDate() - 2);

        it.each([
            [mappedFunctions.date.equal, baseDate, baseDate, true],
            [mappedFunctions.date.equal, baseDate, nowPlusTwo, false],
            [mappedFunctions.date.equal, baseDate, nowMinusTwo, false],
            [mappedFunctions.date.not_equal, baseDate, baseDate, false],
            [mappedFunctions.date.not_equal, baseDate, nowPlusTwo, true],
            [mappedFunctions.date.not_equal, baseDate, nowMinusTwo, true],
            [mappedFunctions.date.in, baseDate.getDate(), baseDate, true],
            [mappedFunctions.date.in, nowPlusTwo.getDate(), baseDate, false],
            [mappedFunctions.date.in, nowMinusTwo.getDate(), baseDate, false],
            [mappedFunctions.date.not_in, baseDate.getDate(), baseDate, false],
            [mappedFunctions.date.not_in, nowPlusTwo.getDate(), baseDate, true],
            [mappedFunctions.date.not_in, nowMinusTwo.getDate(), baseDate, true],
            [mappedFunctions.date.less, baseDate, baseDate, false],
            [mappedFunctions.date.less, baseDate, nowPlusTwo, true],
            [mappedFunctions.date.less, baseDate, nowMinusTwo, false],
            [mappedFunctions.date.less_or_equal, baseDate, baseDate, true],
            [mappedFunctions.date.less_or_equal, baseDate, nowPlusTwo, true],
            [mappedFunctions.date.less_or_equal, baseDate, nowMinusTwo, false],
            [mappedFunctions.date.greater, baseDate, baseDate, false],
            [mappedFunctions.date.greater, baseDate, nowPlusTwo, false],
            [mappedFunctions.date.greater, baseDate, nowMinusTwo, true],
            [mappedFunctions.date.greater_or_equal, baseDate, baseDate, true],
            [mappedFunctions.date.greater_or_equal, baseDate, nowPlusTwo, false],
            [mappedFunctions.date.greater_or_equal, baseDate, nowMinusTwo, true],
            [mappedFunctions.date.between, baseDate, [baseDate, baseDate], true],
            [mappedFunctions.date.between, baseDate, [nowMinusTwo, nowPlusTwo], true],
            [mappedFunctions.date.between, baseDate, [nowMinusTwo, nowMinusTwo], false],
            [mappedFunctions.date.between, baseDate, [nowPlusTwo, nowPlusTwo], false],
            [mappedFunctions.date.between, baseDate, [nowPlusTwo, nowMinusTwo], false],
            [mappedFunctions.date.not_between, baseDate, [baseDate, baseDate], false],
            [mappedFunctions.date.not_between, baseDate, [nowMinusTwo, nowPlusTwo], false],
            [mappedFunctions.date.not_between, baseDate, [nowMinusTwo, nowMinusTwo], true],
            [mappedFunctions.date.not_between, baseDate, [nowPlusTwo, nowPlusTwo], true],
            [mappedFunctions.date.not_between, baseDate, [nowPlusTwo, nowMinusTwo], true],
            [mappedFunctions.date.is_null, baseDate, undefined, false],
            [mappedFunctions.date.is_null, nowPlusTwo, undefined, false],
            [mappedFunctions.date.is_null, nowMinusTwo, undefined, false],
            [mappedFunctions.date.is_null, null, undefined, true],
            [mappedFunctions.date.is_null, undefined, undefined, true],
            [mappedFunctions.date.is_not_null, baseDate, undefined, true],
            [mappedFunctions.date.is_not_null, nowPlusTwo, undefined, true],
            [mappedFunctions.date.is_not_null, nowMinusTwo, undefined, true],
            [mappedFunctions.date.is_not_null, null, undefined, false],
            [mappedFunctions.date.is_not_null, undefined, undefined, false]
        ])("should check %s with %s and %s returns %s", (fn, a, b, expected) => {
            expect(fn(a, b)).toBe(expected);
        });
    });
});
